name: Deploy Theme (Stable)
on:
  push:	
    branches:	
      - stable
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@stable
      - name: Deploy Ghost Theme
        uses: TryGhost/action-deploy-theme@v1.2.1
        with:
          api-url: ${{ secrets.GHOST_ADMIN_API_URL }}
          api-key: ${{ secrets.GHOST_ADMIN_API_KEY }}
